# Generated by Django 5.0.1 on 2024-02-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ims_brand_status_alter_ims_product_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ims_product',
            name='minimum_order',
            field=models.FloatField(default=0),
        ),
    ]
